 var courses = [];

 function makeCourse(name, req, req2, req3) {
     var course = {};
     course.name = name;
     course.req = req;
     return course;
 }
courses.push(makeCourse("Adv Dance", "AD"));
courses.push(makeCourse("Beg Dance", "AD"));
courses.push(makeCourse("Dance", "AD"));
courses.push(makeCourse("Dance - Ballet", "AD"));
courses.push(makeCourse("Dance - Jazz", "AD"));
courses.push(makeCourse("Dance - Musical Theater", "AD"));
courses.push(makeCourse("Interm Adv Dance", "AD"));
courses.push(makeCourse("Interm Dance", "AD"));
courses.push(makeCourse("Interm Dance 1", "AD"));
courses.push(makeCourse("Interm Dance 2", "AD"));
courses.push(makeCourse("Adv Jazz Ensemble", "AM"));
courses.push(makeCourse("Beg Vocal Music", "AM"));
courses.push(makeCourse("Interm Jazz Ensemble", "AM"));
courses.push(makeCourse("Jazz Choir", "AM"));
courses.push(makeCourse("Music Production", "AM"));
courses.push(makeCourse("Musical Theater", "AM"));
courses.push(makeCourse("Production", "AM"));
courses.push(makeCourse("Vocal Ensemble", "AM"));
courses.push(makeCourse("Vocal Revue", "AM"));
courses.push(makeCourse("Vocal Showcase", "AM"));
courses.push(makeCourse("Adv Acting", "AP"));
courses.push(makeCourse("Beg Acting", "AP"));
courses.push(makeCourse("Costume Design", "AP"));
courses.push(makeCourse("Improvisation", "AP"));
courses.push(makeCourse("Interm Acting", "AP"));
courses.push(makeCourse("Mask", "AP"));
courses.push(makeCourse("Musical", "AP"));
courses.push(makeCourse("Playing Shakespeare", "AP"));
courses.push(makeCourse("Production", "AP"));
courses.push(makeCourse("Sketch Comedy TV Writing", "AP"));
courses.push(makeCourse("Stage Combat", "AP"));
courses.push(makeCourse("Stage Management", "AP"));
courses.push(makeCourse("Tech Theater", "AP"));
courses.push(makeCourse("Writing for TV", "AP"));
courses.push(makeCourse("3 D Studio Arts", "AV"));
courses.push(makeCourse("Adv Film", "AV"));
courses.push(makeCourse("Adv Photography", "AV"));
courses.push(makeCourse("Adv Studio Arts", "AV"));
courses.push(makeCourse("Animation", "AV"));
courses.push(makeCourse("Arts Innovation", "AV"));
courses.push(makeCourse("Beg Studio Arts", "AV"));
courses.push(makeCourse("Black and White Photography", "AV"));
courses.push(makeCourse("Ceramics", "AV"));
courses.push(makeCourse("Design and Technology", "AV"));
courses.push(makeCourse("Digital Photography", "AV"));
courses.push(makeCourse("Experimental Photography", "AV"));
courses.push(makeCourse("Fiber Arts", "AV"));
courses.push(makeCourse("Film", "AV"));
courses.push(makeCourse("Film Appreciation", "AV"));
courses.push(makeCourse("Film Documentary", "AV"));
courses.push(makeCourse("Graphic Design & Typography", "AV"));
courses.push(makeCourse("Interm Studio Arts", "AV"));
courses.push(makeCourse("Intro Graphic Design", "AV"));
courses.push(makeCourse("Portfolio", "AV"));
courses.push(makeCourse("Sculpture", "AV"));
courses.push(makeCourse("Studio Arts", "AV"));
courses.push(makeCourse("Entrepreneurship FL", "EF"));
courses.push(makeCourse("Agents of Transformation", "EL"));
courses.push(makeCourse("Beg Speech", "EL"));
courses.push(makeCourse("China", "EL"));
courses.push(makeCourse("Civics", "EL"));
courses.push(makeCourse("Creative Writing", "EL"));
courses.push(makeCourse("Debate", "EL"));
courses.push(makeCourse("Ethics 9", "EL"));
courses.push(makeCourse("France", "EL"));
courses.push(makeCourse("India", "EL"));
courses.push(makeCourse("IS Esperanto", "EL"));
courses.push(makeCourse("Mock Trial", "EL"));
courses.push(makeCourse("Robotics Team", "EL"));
courses.push(makeCourse("Senior Project Course", "EL"));
courses.push(makeCourse("Speech", "EL"));
courses.push(makeCourse("Speech-Debate", "EL"));
courses.push(makeCourse("Student Facilitators", "EL"));
courses.push(makeCourse("Study", "NC"));
courses.push(makeCourse("Study Hall", "NC"));
courses.push(makeCourse("Study Skills", "EL"));
courses.push(makeCourse("Underwater Robotics", "EL"));
courses.push(makeCourse("English 10", "EN"));
courses.push(makeCourse("English 11", "EN"));
courses.push(makeCourse("English 12", "EN"));
courses.push(makeCourse("English 9", "EN"));
courses.push(makeCourse("Chinese 1", "FL"));
courses.push(makeCourse("Chinese 2", "FL"));
courses.push(makeCourse("Chinese 3", "FL"));
courses.push(makeCourse("French 1", "FL"));
courses.push(makeCourse("French 2", "FL"));
courses.push(makeCourse("French 3", "FL"));
courses.push(makeCourse("French 4", "FL"));
courses.push(makeCourse("Hon Chinese 4", "FL"));
courses.push(makeCourse("Hon Chinese 5", "FL"));
courses.push(makeCourse("Hon Chinese 6", "FL"));
courses.push(makeCourse("Hon French 4", "FL"));
courses.push(makeCourse("Hon French 5", "FL"));
courses.push(makeCourse("Hon French 6", "FL"));
courses.push(makeCourse("Hon Spanish 4", "FL"));
courses.push(makeCourse("Hon Spanish 5", "FL"));
courses.push(makeCourse("Hon Spanish 6", "FL"));
courses.push(makeCourse("Spanish 1", "FL"));
courses.push(makeCourse("Spanish 2", "FL"));
courses.push(makeCourse("Spanish 2 (tr)", "FL"));
courses.push(makeCourse("Spanish 3", "FL"));
courses.push(makeCourse("Spanish 4", "FL"));
courses.push(makeCourse("Health 9", "HE"));
courses.push(makeCourse("American History", "HI"));
courses.push(makeCourse("History 10", "HI"));
courses.push(makeCourse("History 12", "HI"));
courses.push(makeCourse("History 12 - PNWH", "HI"));
courses.push(makeCourse("History 9", "HI"));
courses.push(makeCourse("PNWH", "HI"));
courses.push(makeCourse("Innovations 10", "IN"));
courses.push(makeCourse("Adv Algebra", "MA"));
courses.push(makeCourse("Calculus 1", "MA"));
courses.push(makeCourse("Calculus 2", "MA"));
courses.push(makeCourse("Computational Thinking - AI", "CT"));
courses.push(makeCourse("Computational Thinking - Data", "CT"));
courses.push(makeCourse("Geometry", "MA"));
courses.push(makeCourse("Hon Calculus 1", "MA"));
courses.push(makeCourse("Hon Calculus 2", "MA"));
courses.push(makeCourse("Integrated Algebra 10", "MA"));
courses.push(makeCourse("Integrated Algebra 9", "MA"));
courses.push(makeCourse("Math Lab", "MA"));
courses.push(makeCourse("Pre Calculus", "MA"));
courses.push(makeCourse("Software Development", "CT"));
courses.push(makeCourse("Software Development w Honors", "CT"));
courses.push(makeCourse("Health", "HE"));
courses.push(makeCourse("Health 10", "PE"));
courses.push(makeCourse("Health 9", "PE"));
courses.push(makeCourse("PE", "PE"));
courses.push(makeCourse("PE - Outside Credit", "PE"));
courses.push(makeCourse("PE - Strength & Conditioning", "PE"));
courses.push(makeCourse("PE - Yoga", "PE"));
courses.push(makeCourse("Strength and Conditioning", "PE"));
courses.push(makeCourse("Rhetoric 9", "RE"));
courses.push(makeCourse("Adv Chemistry", "SC"));
courses.push(makeCourse("Biology", "SC"));
courses.push(makeCourse("Biotechnology", "SC"));
courses.push(makeCourse("Chemistry", "SC"));
courses.push(makeCourse("Climate Science", "SC"));
courses.push(makeCourse("Conceptual Chemistry", "SC"));
courses.push(makeCourse("Endocrinology", "SC"));
courses.push(makeCourse("Evolution", "SC"));
courses.push(makeCourse("Genetics", "SC"));
courses.push(makeCourse("GIS & Urban Ecology", "SC"));
courses.push(makeCourse("Hon Biology", "SC"));
courses.push(makeCourse("Hon Physics", "SC"));
courses.push(makeCourse("Infectious Diseases", "SC"));
courses.push(makeCourse("Intro to Anatomy", "SC"));
courses.push(makeCourse("Intro to Neuroscience", "SC"));
courses.push(makeCourse("Marine Science", "SC"));
courses.push(makeCourse("Meteorology", "SC"));
courses.push(makeCourse("Physics", "SC"));
courses.push(makeCourse("Robotics", "SC"));
courses.push(makeCourse("Science Innovations", "SC"));
courses.push(makeCourse("Science, Opinion, and Society", "SC"));
courses.push(makeCourse("Scientific Investigation", "SC"));
courses.push(makeCourse("Sustainability", "SC"));
courses.push(makeCourse("TA", "SE"));

 function sortCompare(a, b) {
     return a.name.localeCompare(b.name);
 }
 courses = courses.sort(sortCompare);